### PR TITLE
WIP: gufi_ls updates

### PR DESCRIPTION
**Pull request by calccrypto**
#8

### CODE REVIEW

**Comment by dmanno** [comment]
Getting closer. Seems to be doing recursion by default. Formatting still needs work.

**Comment by calccrypto** [comment]
@dmanno Can you check if that you are running with this change? I am not seeing recursion unless I pass in `-R`.

https://github.com/mar-file-system/GUFI/blob/572723feed1336d8dd51295589af6d5d75c857c9/scripts/gufi_ls#L265

**Comment by calccrypto** [comment]
The only way I can think of to align the rows is to aggregate and scan the results database twice, since there is no global record that keeps track of the width of the columns across threads. Do we want to aggregate?

```
-rw------- 1 0 0 1.0 Date Time Name
-rw------- 1 0 0 4.56K Date Time Name
-rw------- 1 0 0 123.4M  Date Time Name
```

**Comment by calccrypto** [comment]
> The only way I can think of to align the columns is to scan each results database twice, since there is no global record that keeps track of the width of the columns. To align all columns, the results will need to be aggregated in addition to scanning. Do we want to aggregate?
> 
> ```
> -rw------- 1 0 0 1.0 Date Time Name
> -rw------- 1 0 0 4.56K Date Time Name
> -rw------- 1 0 0 123.4M  Date Time Name
> ```

Fixed with c13597f9db4df1b004ad4089814e72b55441e76b. The default width for the size column is 16, but can be changed with the `--size-width` option

**Comment by garygrider** [comment]
To know the maximum width you would need to scan twice or aggregate and scan the aggregate or something like that.
If you use sqlite interactively there is a .width thing  .width auto  but I don’t know how that works and it doesn’t effect bfq really

There is an elegant way to solve this I suppose.  We could add set of fields to the schema to keep width in the summary record and bfwi
since there is this summer routine could keep track of longest field.  Or the rawquery routine could do strlens on everything and update a global.

None of this sounds elegant really, even knowing the widths up front doesn’t help you when you are traversing and printing path.  I suppose
Writing it to a file and use rlwrap or column or similar is possible but again, not elegant in any way.

Seems excessive to me but I am not a user

**Comment by dmanno** [comment]
Directories aren't being handled. We will meet and summarize the discussion and path forward.

**Comment by dmanno** [comment]
Directories aren't being handled. We will meet and summarize the path forward.

**Pull request closed without merging**
